name: 'Setup OpenTofu'
description: 'Imports GPG, installs SOPS and decrypts tfvars'
inputs:
  ssh_public_key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Create SSH Key File
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_public_key }}" > ~/.ssh/id_rsa.pub
