fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: env ANSIBLE_CONFIG=ansible/ansible.cfg .venv/bin/ansible-lint -c ansible/.ansible-lint ansible/
        language: system
        files: ^ansible/.*\.(yaml|yml)$
        pass_filenames: false
  - repo: local
    hooks:
      - id: gitops-yaml-check
        name: gitops-yaml-check
        entry: ./scripts/githooks/pre-commit-yaml-check
        language: script
        always_run: true
        pass_filenames: false
        verbose: true
  - repo: local
    hooks:
      - id: encrypted-secrets-check
        name: encrypted-secrets-check
        entry: ./scripts/githooks/pre-commit-secrets-check
        language: script
        always_run: true
        pass_filenames: false
        verbose: true
