creation_rules:
  - path_regex: opentofu/infra/.*\.tfvars$
    pgp: "640170DE796E3CC2C1EA7E9D4DA395A9634B5E40" 
  - path_regex: ansible/roles/tang/files/tang-keys/.*\.jwk$
    pgp: "640170DE796E3CC2C1EA7E9D4DA395A9634B5E40" 
