creation_rules:
  - path_regex: opentofu/.*\.tfvars$
    age: "age1erlt7mzurdy2mzyytm57ycxq4jl6yp8f7eq73pfvxcyc89kxafrs6reesp"

  - path_regex: ansible/roles/tang/files/tang-keys/.*\.jwk$
    age: "age1erlt7mzurdy2mzyytm57ycxq4jl6yp8f7eq73pfvxcyc89kxafrs6reesp"

    # filtering only files of 'kind: Secret' happens inside the pre-commit script
  - path_regex: gitops/.*\.ya?ml$
    age: "age1erlt7mzurdy2mzyytm57ycxq4jl6yp8f7eq73pfvxcyc89kxafrs6reesp"
    encrypted_regex: '^(data|stringData)$'
