module "vm" {
  source      = "../modules/proxmox/vm"
  vm_name     = var.local_runner_name
  vm_id     = var.local_runner_vm_id
  ipv4_address  = var.local_runner_ipv4
  ipv4_gateway = var.local_runner_gateway_ipv4
  ipv6_address  = var.local_runner_ipv6
  ipv6_gateway = var.local_runner_gateway_ipv6
  cpu_cores = var.local_runner_cpu_cores
  os = var.local_runner_os
  memory = var.local_runner_memory
  storage = var.local_runner_storage
  size = var.local_runner_size
  username = var.local_runner_username
  hostname = var.local_runner_hostname
  vlan_id = var.local_runner_vlan_id
  public_ssh_key = var.shared_ssh_public_key_file
  pve_node = var.shared_pve_node
  template_id = var.shared_vm_template_id
}
