---
- name: Install WireGuard and dependencies
  ansible.builtin.apt:
    name:
      - wireguard
    state: present
    update_cache: true

- name: Ensure WireGuard configuration directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Deploy WireGuard configuration
  ansible.builtin.template:
    src: wireguard.conf.j2
    dest: "/etc/wireguard/{{ vault_interface }}.conf"
    mode: '0600'
    owner: root
    group: root
  notify: Restart WireGuard

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start WireGuard service
  ansible.builtin.systemd:
    name: "wg-quick@{{ vault_interface }}"
    enabled: true
    state: started

- name: Deploy Reresolve Script for Live IP Update
  ansible.builtin.template:
    src: reresolve-dns.sh.j2
    dest: "/usr/local/bin/reresolve-dns.sh"
    mode: '0755'
    owner: root
    group: root

- name: Deploy Reresolve Service
  ansible.builtin.template:
    src: wg-reresolve.service.j2
    dest: "/etc/systemd/system/wg-reresolve.service"
    mode: '0755'
    owner: root
    group: root

- name: Deploy Reresolve Timer
  ansible.builtin.template:
    src: wg-reresolve.timer.j2
    dest: "/etc/systemd/system/wg-reresolve.timer"
    mode: '0755'
    owner: root
    group: root

- name: Reload systemd and activate Timer
  ansible.builtin.systemd:
    daemon_reload: true
    name: wg-reresolve.timer
    state: started
    enabled: true
