---
- name: Load secret variables
  ansible.builtin.include_vars:
    file: secrets.yml

- name: "Configure Netplan for static IPv4 and IPv6"
  ansible.builtin.copy:
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0600'
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          eth0:
            addresses:
              - {{ hostvars['shadow']['ansible_host'] }}/24
              - {{ hostvars['shadow']['ansible_host_ipv6'] }}/64
            routes:
              - to: default
                via: {{ dns_gateway_ipv4 }}
              - to: default
                via: {{ dns_gateway_ipv6 }}
  notify: "Apply netplan"
  when: inventory_hostname == 'shadow'

- name: "Apply netplan immediately if changed"
  ansible.builtin.meta: flush_handlers
  when: inventory_hostname == 'shadow'

- name: "Disable systemd-resolved"
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  register: pihole_resolved_status
  failed_when:
    - pihole_resolved_status.failed
    - "'Could not find the requested service' not in pihole_resolved_status.msg"

- name: "Set temporary DNS (Quad9) for installation"
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: "nameserver 9.9.9.9\n"
    owner: root
    group: root
    mode: '0644'
    force: true

- name: "Install Unbound"
  ansible.builtin.apt:
    name: unbound
    state: present
    update_cache: true

- name: "Download Root Hints"
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.root
    dest: /var/lib/unbound/root.hints
    owner: root
    group: root
    mode: '0644'

- name: "Configure Unbound"
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    content: |
      server:
          verbosity: 0
          interface: 127.0.0.1
          port: 5335
          do-ip4: yes
          do-udp: yes
          do-tcp: yes
          root-hints: "/var/lib/unbound/root.hints"
          private-address: 192.168.0.0/16
          private-address: 172.16.0.0/12
          private-address: 10.0.0.0/8
    owner: root
    group: root
    mode: '0644'
  notify: Restart Unbound

- name: "Ensure Unbound is running NOW with new config"
  ansible.builtin.meta: flush_handlers

- name: "Create Pi-hole config dir"
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Preseed SetupVars for skipping IP-check on LXC
  ansible.builtin.copy:
    dest: /etc/pihole/setupVars.conf
    content: |
      PIHOLE_INTERFACE={{ network_interface }}
      IPV4_ADDRESS={{ ansible_default_ipv4.address }}/24
    mode: '0644'
  when: ansible_virtualization_type == 'lxc'

- name: "Download Installer"
  ansible.builtin.get_url:
    url: https://install.pi-hole.net
    dest: /tmp/install-pihole.sh
    mode: '0744'

- name: "Run Installer"
  ansible.builtin.command: "/tmp/install-pihole.sh --unattended"
  args:
    creates: /usr/local/bin/pihole
  notify:
    - "Update Pi-hole gravity"

- name: "Set local DNS to localhost (Pi uses itself now)"
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: "nameserver 127.0.0.1"
    owner: root
    group: root
    mode: '0644'

- name: "Configure pihole.toml via cli"
  vars:
    upstreams_list:
      - "{{ vault_pihole_dns_upstream }}"
      - "/{{ custom_domain }}/{{ dns_gateway_ipv4 }}"
      - "/{{ custom_domain }}/{{ dns_gateway_ipv6 }}"
      - "/{{ dns_gateway_ipv4.split('.')[:3] | reverse | join('.') }}.in-addr.arpa/{{ dns_gateway_ipv4 }}"
      - "/ip6.arpa/{{ dns_gateway_ipv6 }}"
  ansible.builtin.command: "pihole-FTL --config {{ item.key }} {{ item.value }}"
  loop:
    - { key: 'dns.interface', value: '{{ network_interface }}' }
    - { key: 'dns.listeningMode', value: 'all' }
    - { key: 'dns.bogusPriv', value: 'false' }
    - { key: 'dns.domainNeeded', value: 'false' }
    - { key: 'dns.upstreams', value: "'{{ upstreams_list | to_json }}'" }
  changed_when: true

- name: "Ensure Web Interface Password is set"
  ansible.builtin.command: "pihole setpassword {{ vault_pihole_web_password }}"
  no_log: true
  changed_when: false
