locals {
  proxmox_host_ip = split(":", split("/", var.shared_virtual_environment_endpoint)[2])[0]
}

resource "local_file" "ansible_inventory" {
  filename = "../../ansible/inventory.ini"
  content  = <<EOT
# --------------------------------------------------------------------------
# ! WARNING: THIS FILE IS AUTOGENERATED BY OPENTOFU (/opentofu/infra)!
# Any manual changes to this file will be overwritten during the next run.
# Generated on: ${timestamp()}
# --------------------------------------------------------------------------
[proxmox_lxc]
${module.tang.hostname} ansible_host=${split("/", module.tang.ipv4_address)[0]}
${module.prowl.hostname} ansible_host=${split("/", module.prowl.ipv4_address)[0]} ipv6_address=${split("/", module.prowl.ipv6_address)[0]}

[proxmox_vm]
# managed in /opentofu/runner
runner_alpha ansible_host=192.168.13.253 ansible_user=twoy

[dns_group]
# shadow is not managed by OpenTofu
shadow ansible_host=192.168.13.251 ipv6_address=fd69:efa6:36fd:0::251 keepalived_role=MASTER keepalived_priority=100 ansible_user=not32olo
${module.prowl.hostname} keepalived_role=BACKUP keepalived_priority=80

[dns_group:vars]
virtual_ip_v4=192.168.13.249/24
virtual_ip_v6=fd69:efa6:36fd::249/64
network_interface=eth0

[tang_group]
${module.tang.hostname}

[runner_group]
runner_alpha

[all:children]
proxmox_lxc
proxmox_vm
tang_group
runner_group
dns_group

[all:vars]
ansible_user=root
# set via ssh-agent
ansible_ssh_private_key_file=""
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ironhide = 192.168.13.117
ironhide_wifi = 192.168.13.118
sentinel = 192.168.13.205
pihole_ninja = 192.168.13.10
pve_ip = ${local.proxmox_host_ip}
shared_network_gateway = ${var.shared_network_gateway}
shared_network_gateway_ipv6 = ${var.shared_network_gateway_ipv6}
EOT

depends_on = [ module.tang, module.prowl ]
}

module "tang" {
  source = "../modules/proxmox/lxc"

  pve_node         = var.shared_virtual_environment_node
  vm_id            = var.tang_vm_id
  hostname         = var.tang_hostname
  template_file_id = var.shared_lxc_template_file_id

  ipv4_address     = var.tang_ipv4_address
  gateway          = var.shared_network_gateway

  ipv6_address     = var.tang_ipv6_address
  ipv6_gateway     = var.shared_network_gateway_ipv6

  ssh_public_key_file = var.shared_ssh_public_key_file
  root_password       = var.tang_root_password

  datastore_id     = var.tang_datastore_id
  datastore_size   = var.tang_datastore_size
  start_on_boot    = var.tang_start_on_boot
}

module "prowl" {
  source = "../modules/proxmox/lxc"

  pve_node         = var.shared_virtual_environment_node
  vm_id            = var.prowl_vm_id
  hostname         = var.prowl_hostname
  template_file_id = var.shared_lxc_template_file_id

  ipv4_address     = var.prowl_ipv4_address
  gateway          = var.shared_network_gateway

  ipv6_address     = var.prowl_ipv6_address
  ipv6_gateway     = var.shared_network_gateway_ipv6

  ssh_public_key_file = var.shared_ssh_public_key_file
  root_password       = var.prowl_root_password

  datastore_id     = var.prowl_datastore_id
  datastore_size   = var.prowl_datastore_size
  start_on_boot    = var.prowl_start_on_boot
}
