locals {
  _networks = {
    trusted = "10.0.10.0/24"
    core = "10.0.20.0/24"
    iot = "10.0.21.0/24"
    lab = "10.0.22.0/24"
    guest = "10.0.30.0/24"
    work = "10.0.40.0/24"
  }

  _ula_prefixes = {
    trusted  = "fd00:10::"
    core     = "fd00:20::"
    iot       = "fd00:21::"
    lab    = "fd00:22::"
    guest     = "fd00:30::"
    work      = "fd00:40::"
  }

  vlans = {
    trusted = {
      id      = 10
      network = local._networks.trusted
      gateway_ipv4 = cidrhost(local._networks.trusted, 1)
      ula_prefix   = local._ula_prefixes.trusted
      gateway_ipv6 = "${local._ula_prefixes.trusted}1"
    }

    core = {
      id      = 20
      network = local._networks.core
      gateway_ipv4 = cidrhost(local._networks.core, 1)
      ula_prefix   = local._ula_prefixes.core
      gateway_ipv6 = "${local._ula_prefixes.core}1"
    }

    iot = {
      id      = 21
      network = local._networks.iot
      gateway_ipv4 = cidrhost(local._networks.iot, 1)
      ula_prefix   = local._ula_prefixes.iot
      gateway_ipv6 = "${local._ula_prefixes.iot}1"
    }

    lab = {
      id      = 22
      network = local._networks.lab
      gateway_ipv4 = cidrhost(local._networks.lab, 1)
      ula_prefix   = local._ula_prefixes.lab
      gateway_ipv6 = "${local._ula_prefixes.lab}1"
    }

    guest = {
      id      = 30
      network = local._networks.guest
      gateway_ipv4 = cidrhost(local._networks.guest, 1)
      ula_prefix   = local._ula_prefixes.guest
      gateway_ipv6 = "${local._ula_prefixes.guest}1"
    }

    work = {
      id      = 40
      network = local._networks.work
      gateway_ipv4 = cidrhost(local._networks.work, 1)
      ula_prefix   = local._ula_prefixes.work
      gateway_ipv6 = "${local._ula_prefixes.work}1"
    }
  }

  # Fully managed means automatically created with IaC (OpenTofu) and / or configured with CaC (Ansible)
  # Semi managed means the host was created manually but is configured CaC
  # Unmanaged means everything is configured manually

  fully_managed_hosts = {
    # ----------------------- WARNING -------------------------
    # Runners are primarily configured in /runner where their configuration actually live. Changes here require changes inside /runner and vice versa.
    # ---------------------------------------------------------
    runner_alpha = {
       hostname = "runner-alpha"
       ipv4_address = "${cidrhost(local.vlans.lab.network, 2)}"
       ipv6_address = "${local.vlans.lab.ula_prefix}2"
       user = "runner_alpha"
    }
    # ---------------------------------------------------------

    tang = {
       hostname = "tang"
       ipv4_address = "${cidrhost(local.vlans.core.network, 6)}"
       ipv6_address = "${local.vlans.core.ula_prefix}6"
    }

    prowl = {
       hostname = "prowl"
       ipv4_address = "${cidrhost(local.vlans.core.network, 5)}"
       ipv6_address = "${local.vlans.core.ula_prefix}5"
    }
  }

  semi_managed_hosts = {
    shadow = {
       hostname = "shadow"
       ipv4_address = "${cidrhost(local.vlans.core.network, 2)}"
       ipv6_address = "${local.vlans.core.ula_prefix}2"
       user = "not32olo"
    }

    // TODO: Solved by #18
    sentinel = {
      hostname = "sentinel"
      ipv4_address = null
      ipv6_address = null

    }
  }

  unmanaged_hosts = {
      ninja = {
        hostname = "ninja"
        ipv4_address = split(":", split("/", var.shared_pve_endpoint)[2])[0]
        ipv6_address = "${local.vlans.core.ula_prefix}2"

      }

      ironhide = {
       hostname = "ironhide"
       ipv4_address = "${cidrhost(local.vlans.trusted.network, 2)}"
       ipv6_address = "${local.vlans.trusted.ula_prefix}2"
      }
  }

  dns_vip = {
    ipv4_address = "${cidrhost(local.vlans.core.network, 10)}"
    ipv6_address = "${local.vlans.core.ula_prefix}10"
  }
}

resource "local_file" "ansible_inventory" {
  filename = "../../ansible/inventory.ini"
  content  = <<EOT
# ----------------------- WARNING -------------------------
# THIS FILE IS AUTOGENERATED BY OPENTOFU (/opentofu/infra/main.tf)
# Any manual changes to this file will be overwritten during the next run of tofu apply.
# Generated on: ${timestamp()}
# ---------------------------------------------------------
[proxmox_lxc]
${local.fully_managed_hosts.tang.hostname} ansible_host=${local.fully_managed_hosts.tang.ipv4_address}
${local.fully_managed_hosts.prowl.hostname} ansible_host=${local.fully_managed_hosts.prowl.ipv4_address} ansible_host_ipv6=${local.fully_managed_hosts.prowl.ipv6_address}

[proxmox_vm]
${local.fully_managed_hosts.runner_alpha.hostname} ansible_host=${local.fully_managed_hosts.runner_alpha.ipv4_address}  ansible_user=${local.fully_managed_hosts.runner_alpha.user}

[dns_group]
${local.semi_managed_hosts.shadow.hostname} ansible_host=${local.semi_managed_hosts.shadow.ipv4_address} ansible_host_ipv6=${local.semi_managed_hosts.shadow.ipv6_address} keepalived_role=MASTER keepalived_priority=100 ansible_user=${local.semi_managed_hosts.shadow.user}
${local.fully_managed_hosts.prowl.hostname} keepalived_role=BACKUP keepalived_priority=80

[dns_group:vars]
network_interface=eth0
dns_gateway_ipv4=${local.vlans.core.gateway_ipv4}
dns_gateway_ipv6=${local.vlans.core.gateway_ipv6}
custom_domain=x3dh.de

[tang_group]
${local.fully_managed_hosts.tang.hostname}

[runner_group]
${local.fully_managed_hosts.runner_alpha.hostname}

[all:children]
proxmox_lxc
proxmox_vm
tang_group
runner_group
dns_group

[all:vars]
dns_vip_ipv4_address=${local.dns_vip.ipv4_address}
dns_vip_ipv4_address=${local.dns_vip.ipv6_address}

# ansible settings
ansible_user=root
# configured with ssh-agent
ansible_ssh_trusted_key_file=""
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT

depends_on = [ module.tang, module.prowl ]
}

module "tang" {
  source = "../modules/proxmox/lxc"

  pve_node         = var.shared_pve_node
  vm_id            = 200
  hostname         = "${local.fully_managed_hosts.tang.hostname}"
  vlan_id          = var.local_vlan_id
  template_file_id = var.shared_lxc_template_file_id

  ipv4_address     = "${local.fully_managed_hosts.tang.ipv4_address}/24"
  gateway          = local.vlans.core.gateway_ipv4

  ipv6_address     = "${local.fully_managed_hosts.tang.ipv6_address}/64"
  ipv6_gateway     = local.vlans.core.gateway_ipv6

  ssh_public_key_file = var.shared_ssh_public_key_file
  root_password       = var.local_tang_root_password

  datastore_id     = var.shared_datastore_id
  datastore_size   = var.shared_datastore_size
  start_on_boot    = var.shared_start_on_boot
}

module "prowl" {
  source = "../modules/proxmox/lxc"

  pve_node         = var.shared_pve_node
  vm_id            = 201
  hostname         = "${local.fully_managed_hosts.prowl.hostname}"
  vlan_id          = var.local_vlan_id
  template_file_id = var.shared_lxc_template_file_id

  ipv4_address     = "${local.fully_managed_hosts.prowl.ipv4_address}/24"
  gateway          = local.vlans.core.gateway_ipv4

  ipv6_address     = "${local.fully_managed_hosts.prowl.ipv6_address}/64"
  ipv6_gateway     = local.vlans.core.gateway_ipv6

  ssh_public_key_file = var.shared_ssh_public_key_file
  root_password       = var.local_prowl_root_password

  datastore_id     = var.shared_datastore_id
  datastore_size   = var.shared_datastore_size
  start_on_boot    = var.shared_start_on_boot
}
