locals {
  _networks = {
    trusted = "10.0.10.0/24"
    core = "10.0.20.0/24"
    iot = "10.0.21.0/24"
    lab = "10.0.22.0/24"
    guest = "10.0.30.0/24"
    work = "10.0.40.0/24"
  }

  _ula_prefixes = {
    trusted  = "fd00:10::"
    core     = "fd00:20::"
    iot       = "fd00:21::"
    lab    = "fd00:22::"
    guest     = "fd00:30::"
    work      = "fd00:40::"
  }

  vlans = {
    trusted = {
      id      = 10
      network = local._networks.trusted
      gateway_ipv4 = cidrhost(local._networks.trusted, 1)
      ula_prefix   = local._ula_prefixes.trusted
      gateway_ipv6 = "${local._ula_prefixes.trusted}1"
    }

    core = {
      id      = 20
      network = local._networks.core
      gateway_ipv4 = cidrhost(local._networks.core, 1)
      ula_prefix   = local._ula_prefixes.core
      gateway_ipv6 = "${local._ula_prefixes.core}1"
    }

    iot = {
      id      = 21
      network = local._networks.iot
      gateway_ipv4 = cidrhost(local._networks.iot, 1)
      ula_prefix   = local._ula_prefixes.iot
      gateway_ipv6 = "${local._ula_prefixes.iot}1"
    }

    lab = {
      id      = 22
      network = local._networks.lab
      gateway_ipv4 = cidrhost(local._networks.lab 1)
      ula_prefix   = local._ula_prefixes.lab
      gateway_ipv6 = "${local._ula_prefixes.lab}1"
    }

    guest = {
      id      = 30
      network = local._networks.guest
      gateway_ipv4 = cidrhost(local._networks.guest 1)
      ula_prefix   = local._ula_prefixes.guest
      gateway_ipv6 = "${local._ula_prefixes.guest}1"
    }

    work = {
      id      = 40
      network = local._networks.work
      gateway_ipv4 = cidrhost(local._networks.work, 1)
      ula_prefix   = local._ula_prefixes.work
      gateway_ipv6 = "${local._ula_prefixes.work}1"
    }
  }

  pve_ipv4 = split(":", split("/", var.shared_virtual_environment_endpoint)[2])[0]

  non_iac_hosts = {
      ironhide = {
       ipv4_address = "${cidrhost(local.vlans.trusted.network, 117)}/24"
       ipv6_address = "${local.vlans.trusted.ula_prefix}117/64"
      }
  }
}

resource "local_file" "ansible_inventory" {
  filename = "../../ansible/inventory.ini"
  content  = <<EOT
# --------------------------------------------------------------------------
# ! WARNING: THIS FILE IS AUTOGENERATED BY OPENTOFU (/opentofu/core)!
# Any manual changes to this file will be overwritten during the next run.
# Generated on: ${timestamp()}
# --------------------------------------------------------------------------
[proxmox_lxc]
${module.tang.hostname} ansible_host=${split("/", module.tang.ipv4_address)[0]}
${module.prowl.hostname} ansible_host=${split("/", module.prowl.ipv4_address)[0]} ansible_host_ipv6=${split("/", module.prowl.ipv6_address)[0]}

[proxmox_vm]
# managed in /opentofu/lab
lab_alpha ansible_host=192.168.13.253 ansible_user=twoy

[dns_group]
# shadow is not managed by OpenTofu
shadow ansible_host=192.168.13.251 ansible_host_ipv6=fd69:efa6:36fd:0::251 keepalived_role=MASTER keepalived_priority=100 ansible_user=not32olo
${module.prowl.hostname} keepalived_role=BACKUP keepalived_priority=80

[dns_group:vars]
network_interface=eth0

[tang_group]
${module.tang.hostname}

[lab_group]
lab_alpha

[all:children]
proxmox_lxc
proxmox_vm
tang_group
lab_group
dns_group

[all:vars]
# hosts that are not managed by OpenTofu
ironhide_ipv4 = 192.168.13.117
ironhide_wifi_ipv4 = 192.168.13.118
sentinel_ipv4 = 192.168.13.205
pve_ipv4 = ${local.pve_ipv4}
shared_network_gateway = ${var.shared_network_gateway}
shared_network_gateway_ipv6 = ${var.shared_network_gateway_ipv6}

virtual_ipv4=192.168.13.249
virtual_ipv6=fd69:efa6:36fd::249

# ansible settings
ansible_user=root
# configured with ssh-agent
ansible_ssh_trusted_key_file=""
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT

depends_on = [ module.tang, module.prowl ]
}

module "tang" {
  source = "../modules/proxmox/lxc"

  pve_node         = var.shared_virtual_environment_node
  vm_id            = 200
  hostname         = "tang"
  vlan_id          = null
  template_file_id = var.shared_lxc_template_file_id

  ipv4_address     = "${cidrhost(local.vlans.core.network, 2)}/24"
  gateway          = local.vlans.core.gateway_ipv4

  ipv6_address     = "${local.vlans.core.ula_prefix}2/64"
  ipv6_gateway     = local.vlans.core.gateway_ipv6

  ssh_public_key_file = var.shared_ssh_public_key_file
  root_password       = var.tang_root_password

  datastore_id     = var.default_datastore_id
  datastore_size   = var.default_datastore_size
  start_on_boot    = var.default_start_on_boot
}

module "prowl" {
  source = "../modules/proxmox/lxc"

  pve_node         = var.shared_virtual_environment_node
  vm_id            = var.prowl_vm_id
  hostname         = var.prowl_hostname
  vlan_id          = var.vlan_id_core
  template_file_id = var.shared_lxc_template_file_id

  ipv4_address     = var.prowl_ipv4_address
  gateway          = var.shared_network_gateway

  ipv6_address     = var.prowl_ipv6_address
  ipv6_gateway     = var.shared_network_gateway_ipv6

  ssh_public_key_file = var.shared_ssh_public_key_file
  root_password       = var.prowl_root_password

  datastore_id     = var.prowl_datastore_id
  datastore_size   = var.prowl_datastore_size
  start_on_boot    = var.prowl_start_on_boot
}
