name: 'Install Environment'
description: 'Installs venv, pip packages, other binaries and Ansible collections'
inputs:
  ansible_vault_password:
    description: 'Vault password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Environment
      uses: actions/cache@v4
      with:
        path: |
          .venv
          ./ansible/collections
        key: ${{ runner.os }}-ansible-${{ hashFiles('./requirements.txt', './ansible/requirements.yml') }}
        restore-keys: |
          ${{ runner.os }}-ansible-

    - name: Run Install Script
      shell: bash
      run: ./scripts/install.sh

    - name: Create Ansible Vault Pass File
      shell: bash
      run: |
        echo "${{ inputs.ansible_vault_password }}" > /root/.ansible_vault_pass
        chmod 600 /root/.ansible_vault_pass
