apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-block
  annotations:
    argocd.argoproj.io/sync-wave: "0"
provisioner: csi.truenas.io
parameters:
  protocol: nvmeof
  pool: "fast"
  datasetPath: "k8s/zvols"
  compression: "lz4"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
