apiVersion: v1
kind: Secret
metadata:
    name: truenas-creds
    namespace: truenas-csi
    annotations:
        argocd.argoproj.io/sync-wave: "0"
stringData:
    truenas_url: ENC[AES256_GCM,data:gSVa/FTdOvzy1Mnlc3sMBA==,iv:KgNxcuHX35BapTFSr60UMVoF31++531Em2Fpw4CcjAY=,tag:K7MUWQXBrw0IRfuCubeQPg==,type:str]
    truenas_api_key: ENC[AES256_GCM,data:/Vyu3/wqpTNKJWiQqpppVwICdwerIrhVCai7+RXTegkrAnpJq8s6S7M144QcnTI9c4ffHjel4VyQyRZCx1GtvK7q,iv:9PehA7YnAjYb/wqwogYrQvMTeREp949ssvCy66Z00sU=,tag:KCfyOMSvQpZPzcB0dlOCEg==,type:str]
    truenas_insecure: ENC[AES256_GCM,data:E9xalw==,iv:XS36YfFANnRjGALGB86EXPSLmbkKOhVKcwUgD8z4pro=,tag:wt4uX+oRpdBxekdWuilEqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1erlt7mzurdy2mzyytm57ycxq4jl6yp8f7eq73pfvxcyc89kxafrs6reesp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQmZEZ2hmd0dRYk9VYnZL
            WW4zcGloWkExaDIwVlhwN2pUN3U2Y3luYWpvCnRJQWttWEZqQVEyemtlZ1RpK2w4
            SEZ6U1lHSmNKamhGUjhXTEJnSlMvS00KLS0tIHFuUFY0YUpKNGQ1TVZIbWJHalQv
            N0JtczZBRXdlalg2Rm5uRERqOXFwMzAKqxpThS/iry+xUYtrCktfs+wTCZFzC2Bq
            RQvGDJ8M1UFBmTNDyMa9y5v/LPa/By0n463pNJzZrQZ1BJJ0csiRUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T11:16:29Z"
    mac: ENC[AES256_GCM,data:cWHLE0AXBVM0BTy0jNS7D3V5zOsAyjvEu8vf40C+kAHTAUd+6SUHTFGgzY9wYEuMv/HQmeGj2HM3c+sv/MXn3LhdnKm1hc/k/BkA0mvwdQNqIQme8uDG1q/jAzjZ4PGo06JwJZiQy2KZx75pqjiLBnjiRt2ARGrNlAwwYE8Y0f0=,iv:ODq4YK1FdDvRsICsrqTiq8O6x02LlhJ5dj/UXDcidzk=,tag:KxLCuhQBRtkvs7zpfqq29Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
