apiVersion: v1
kind: Secret
metadata:
    name: truenas-creds
    namespace: truenas-csi
    annotations:
      argocd.argoproj.io/sync-wave: "0"
stringData:
    truenas_url: ENC[AES256_GCM,data:s+ggImqkNYuPAcvLktz9pA==,iv:ENdInTz4CRnp019WUQdPd125qTYnmQS0n7NGh9T0xfM=,tag:uDUKRnjzLV5DB1IfyYmkJw==,type:str]
    truenas_api_key: ENC[AES256_GCM,data:oNcJBHbLJDx4U+z1PwvGtCJk8gjD/m/payZZyUq1g/cfc/tTdrLbRw41NBg1JCaODXwa5UfRzv8NB13NFbKfP2Hy,iv:PLbkDbu7nyxu1DGijtZ082EKaUiV+a1hpdXR6P/BaA0=,tag:Zky+i2IxWbOCEzTVxE1wjQ==,type:str]
    truenas_insecure: ENC[AES256_GCM,data:aebPrQ==,iv:FHFzNET5inopImw8K6poeA0o8dCsVQ0OuDBfpUsqpQs=,tag:bxu+16ix3tKUuI036CJpnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1erlt7mzurdy2mzyytm57ycxq4jl6yp8f7eq73pfvxcyc89kxafrs6reesp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRGpISUdXZGw0ZXhrd0lL
            Yit3UDhGRnR0NC92YW8xSitGdXA4VEN4NEZjCjZlZkFrd09LeWtOYlY2UVBqWjZV
            YWh5SjloNzNjdE96cDkwcmhSeXVRZTAKLS0tIHZ1UUczMmtLSVA0TkE0MFhrVXBU
            cnE1Nzhyb3JVSmVyWjBuYWlldS9Cbk0KaZTN+G/Dj268SImr9w1E4v/j2FueMwdQ
            D/Jgk3msHLEKjLe/BfcWhiJRZfSJQE6CSwplMIMAOi/jThtmHV9JNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T15:39:52Z"
    mac: ENC[AES256_GCM,data:FMldS+h8nfKVsr+VLssFsVwdfn/hnF3i8JmMQVSRb3K6hZZV+fb31+VfTJ0/vxG8y1Z7dAwAxEBF4Fwz1xWV9K/lputbcGkaPCJds2envRCpkWYVvEqEJRvx5XlYdhXkX29lQYi7vs+rjqPzzJy8B7okatMp3Z+NvM/0jfM5nls=,iv:xUCJU798mgU9rgPXCESC4FpV4uCEY77/VM0kwK3suFI=,tag:AEwT2Q1EGURAa/M/r9ahnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
