---
- name: Setup ninja (Proxmox VE)
  hosts: proxmox_ve
  become: true
  roles:
    - { role: systemd_resolved, tags: ['systemd_resolved'] }
    - { role: duckdns, tags: ['duckdns'] }
    - { role: wireguard, tags: ['wireguard'] }

- name: Setup DNS servers
  hosts: dns_group
  become: true
  roles:
    - { role: apt_upgrade, tags: ['apt_upgrade'] }
    - { role: common, tags: ['common'] }
    - { role: pihole, tags: ['pihole'] }
    - { role: keepalived_pihole, tags: ['pihole', 'keepalived'] }

- name: Setup tang server
  hosts: tang_group
  become: true
  roles:
    - { role: apt_upgrade, tags: ['apt_upgrade'] }
    - { role: common, tags: ['common'] }
    - { role: tang, tags: ['tang'] }

- name: Setup unifi-controller
  hosts: unifi_group
  become: true
  roles:
    - { role: apt_upgrade, tags: ['apt_upgrade', 'unifi_group'] }
    - { role: common, tags: ['common', 'unifi_group'] }
    - { role: install_unifi, tags: ['install_unifi', 'unifi_group'] }
