---
- name: Setup ninja (Proxmox VE)
  hosts: proxmox_ve
  become: true
  roles:
    - { role: systemd_resolved, tags: ['systemd_resolved'] }
    - { role: duckdns, tags: ['duckdns'] }
    - { role: wireguard, tags: ['wireguard'] }

- name: Setup Proxmox guests
  hosts:
  - proxmox_lxc
  - proxmox_vm
  become: true
  roles:
    - { role: proxmox_guests, tags: ['proxmox_guests'] }

- name: Setup DNS servers
  hosts: dns_group
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: pihole, tags: ['pihole'] }
    - { role: keepalived_pihole, tags: ['pihole', 'keepalived'] }

- name: Setup docker_hosts
  hosts: docker_hosts_group
  become: true
  roles:
    - { role: docker, tags: ['docker'] }

- name: Setup portainer server
  hosts: portainer_group
  become: true
  roles:
    - { role: docker_compose_portainer, tags: ['docker_compose_portainer'] }

- name: Setup portainer agents
  hosts: docker_agents_group
  become: true
  roles:
    - { role: docker_compose_portainer_agents, tags: ['docker_compose_portainer_agents'] }

- name: Setup proxy server
  hosts: proxy_group
  become: true
  roles:
    - { role: docker_compose_npm, tags: ['docker_compose_npm'] }

- name: Setup tang server
  hosts: tang_group
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: tang, tags: ['tang'] }

- name: Setup unifi-controller
  hosts: unifi_group
  become: true
  roles:
    - { role: common, tags: ['common', 'unifi_group'] }
    - { role: install_unifi, tags: ['install_unifi', 'unifi_group'] }


