---
- name: Setup Proxmox VE hosts
  hosts: proxmox_cluster
  become: true
  roles:
    - { role: proxmox_qdevice, tags: ['qdevice'] }
    - { role: proxmox_storage, tags: ['truenas'] }
    - { role: prepare_lxc_volume, tags: ['prepare_lxc_volume'] }

# //TODO: Temporary until primus has dedicated vpn connection to sentinel with updated host_vars/primus.yml
- name: Setup Proxmox VE hosts
  hosts: ninja
  become: true
  roles:
    - { role: duckdns, tags: ['duckdns'] }
    - { role: wireguard, tags: ['wireguard'] }

- name: Setup Proxmox guests
  hosts:
  - proxmox_lxc
  - proxmox_vm
  become: true
  roles:
    - { role: proxmox_guests, tags: ['proxmox_guests'] }

- name: Setup DNS servers
  hosts: dns_group
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: pihole, tags: ['pihole'] }
    - { role: keepalived_pihole, tags: ['pihole', 'keepalived'] }

- name: Setup Raspberry PI
  hosts: shadow
  become: true
  roles:
    - { role: pi_qdevice, tags: ['qdevice'] }

- name: Setup docker_hosts
  hosts: docker_hosts_group
  become: true
  roles:
    - { role: docker, tags: ['docker'] }

- name: Setup proxy server
  hosts: proxy_group
  become: true
  roles:
    - { role: docker_compose_npm, tags: ['docker_compose_npm'] }

- name: Setup unifi
  hosts: z1-unifi
  become: true
  roles:
    - { role: docker_compose_unifi, tags: ['docker_compose_unifi'] }

- name: Setup rocketchat
  hosts: z1-rocketchat
  become: true
  roles:
    - { role: docker_compose_rocketchat, tags: ['docker_compose_rocketchat'] }

- name: Setup portainer server
  hosts: portainer_group
  become: true
  roles:
    - { role: docker_compose_portainer, tags: ['docker_compose_portainer'] }

- name: Setup portainer agents
  hosts: docker_agents_group
  become: true
  roles:
    - { role: docker_compose_portainer_agents, tags: ['docker_compose_portainer_agents'] }

- name: Setup tang server
  hosts: tang_group
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: tang, tags: ['tang'] }

- name: Setup unifi-controller
  hosts: unifi_group
  become: true
  roles:
    - { role: common, tags: ['common', 'unifi_group'] }
    - { role: install_unifi, tags: ['install_unifi', 'unifi_group'] }


- name: Bootstrap K8s cluster1 nodes
  hosts: k8s_cluster1_nodes
  become: true
  roles:
    - { role: k8s_bootstrapping_common, tags: ['k8s', 'k8s-cluster1', 'k8s-cluster1-common'] }

- name: Bootstrap K8s cluster1 controlplanes
  hosts: k8s_cluster1_controlplanes
  become: true
  roles:
    - { role: k8s_bootstrapping_controlplanes, tags: ['k8s', 'k8s-cluster1', 'k8s-cluster1-controlplanes'] }

- name: Bootstrap K8s cluster1 workers
  hosts: k8s_cluster1_workers
  become: true
  roles:
    - { role: k8s_bootstrapping_workers, tags: ['k8s', 'k8s-cluster1', 'k8s-cluster1-workers'] }

- name: Install CNI in K8s cluster1
  hosts: k8s_cluster1_controlplanes
  become: true
  roles:
    - { role: k8s_bootstrapping_cilium, tags: ['k8s', 'k8s-cluster1', 'k8s-cluster1-cilium'] }

- name: Install GitOps in K8s cluster1
  hosts: k8s_cluster1_controlplanes
  become: true
  roles:
    - { role: k8s_bootstrapping_argocd, tags: ['k8s', 'k8s-cluster1', 'k8s-cluster1-argocd'] }
