---
- name: Setup lxc "runner-alpha"
  hosts: runner_group
  become: yes
  roles:
    - { role: apt_upgrade, tags: ['apt_upgrade'] }
    - { role: docker, tags: ['docker'] }
    - { role: github_runner, tags: ['runner'] }
