#!/bin/bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)
CONFIG_PATH="$PROJECT_ROOT/.sops.yaml"

encrypt_files() {
    local rel_dir=$1
    local extension=$2
    local sops_type=$3

    if [ ! -d "$PROJECT_ROOT/$rel_dir" ]; then
        echo "Info: Directory $rel_dir does not exist. Skipping..."
        return
    fi

    find "$PROJECT_ROOT/$rel_dir" -type f -name "*.$extension" | while read -r file; do
        target_file="$file.enc"
        filename=$(basename "$file")

        # Check for empty source files
        if [ ! -s "$file" ]; then
            echo "ERROR: Skipping empty file $filename."
            exit 1
        fi

        # only encrypt when timestamp of source file is newer than the encrypted version (target_file)
        if [ -f "$target_file" ] && [ "$file" -ot "$target_file" ]; then
            echo "No changes in $rel_dir/$filename. No need to encrypt again."
            continue
        fi

        echo "Encrypting file: $rel_dir/$filename (Type: $sops_type)"


        if sops --encrypt \
             --config "$CONFIG_PATH" \
             --input-type "$sops_type" \
             --output-type "$sops_type" \
             --output "$target_file" \
             "$file"; then

            git add "$target_file"
        else
            echo "ERROR: Encryption failed for $filename. Check your .sops.yaml!"
            exit 1
        fi
    done
}

encrypt_files "opentofu" "tfvars" "dotenv"
encrypt_files "ansible/roles/tang/files/tang-keys" "jwk" "json"


echo "Starting security check for unencrypted secrets..."

UNENCRYPTED_FILES=$(git diff --cached --name-only --diff-filter=d | grep -E "\.(tfvars|jwk)$" | grep -v "\.enc$")

if [ -n "$UNENCRYPTED_FILES" ]; then
    echo "######################################################################"
    echo "ATTENTION: SECURITY RISK DETECTED!"
    echo "The following files are unencrypted in the staging area:"
    echo "$UNENCRYPTED_FILES"
    echo "----------------------------------------------------------------------"
    echo "Committing these files is NOT permitted."
    echo "Please remove them with: git restore --staged <file>"
    echo "######################################################################"
    exit 1
else
    echo "Check passed: No unencrypted secrets found."
fi

exit 0
