name: "Test"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: "Run hello world"
    runs-on: [self-hosted]
    timeout-minutes: 10
    steps:
      - name: Start Timer
        run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Load full history

